#!/bin/sh
go install golang.org/x/tools/cmd/gonew@latest
go install github.com/fatih/gomodifytags@latest
go install golang.org/x/tools/cmd/callgraph@latest
go install golang.org/x/tools/cmd/goimports@latest
go install github.com/nsf/gocode@latest
go install github.com/rogpeppe/godef@latest
go install github.com/zmb3/gogetdoc@latest
go install github.com/lukehoban/go-outline@latest
go install github.com/sqs/goreturns@latest
go install golang.org/x/tools/cmd/gorename@latest
go install github.com/tpng/gopkgs@latest
go install github.com/newhook/go-symbols@latest
go install golang.org/x/tools/cmd/guru@latest
go install golang.org/x/tools/cmd/godoc@latest
go install github.com/fatih/gomodifytags@latest
go install github.com/onsi/ginkgo/v2/ginkgo@latest
go install github.com/davidrjenni/reftools/cmd/fillswitch@latest
go install github.com/davidrjenni/reftools/cmd/fillstruct@latest
go install gotest.tools/gotestsum@latest
go install github.com/segmentio/golines@latest
go install github.com/josharian/impl@latest
go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
go install golang.org/x/vuln/cmd/govulncheck@latest
go install github.com/abenz1267/gomvp@latest
go install go.uber.org/mock/mockgen@latest
go install mvdan.cc/gofumpt@latest
go install github.com/kyoh86/richgo@latest
go install github.com/koron/iferr@latest
go install github.com/searKing/golang/tools/go-enum@latest
